name: Update reports
on:
  schedule:
    # Runs every Sunday at 21:00 UTC between April and October
    - cron: "0 21 * 4-10 0"
  workflow_dispatch:

env:
  EMAIL: stanningleybowlsclub@gmail.com
  USERNAME: SPBC GitHub Action

jobs:
  Update-Reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Configure Git
        run: |
          git pull
          git config --global user.email "${{ env.EMAIL }}"
          git config --global user.name "${{ env.USERNAME }}"
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install-deps
          npx playwright install
      - name: Update reports
        run: npm run get-reports
      - name: Commit and push
        if: always()
        run: |
          git add bowlsnetReports/*
          git commit -m 'updated reports'
          git push
